# Generated by Django 4.1.3 on 2022-11-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoiceVault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
